title: Oro-oro-ponoro-poron

theme: minima

permalink: /:path/:basename/

page_excerpts: true
excerpt_separator: <!--spoiler-->

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
